name: Android CI with Gradle

definitions:
  steps:
    - &jdk11
      name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        distribution: 'adopt'
        java-version: '11'
    - &cacheGradleWrapper
      name: Store Gradle Binnary
      uses: actions/cache@v1
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - &cacheGradleCaches
      name: Store Gradle Caches
      uses: actions/cache@v1.1.2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    name: Run Unit Tests & Perform Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - *jdk11
      - *cacheGradleWrapper
      - *cacheGradleCaches
      - name: Gradle Check
        run: bash ./gradlew check --stacktrace

  apk:
    name: Generate APK
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - *jdk11
      - *cacheGradleWrapper
      - *cacheGradleCaches
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
